Project details page v2
milestep/Portal pull request #146
Opened 2022-03-22 17:32 UTC by asmlvsk

2022-03-23 12:37 UTC, NazarYanchyshyn requested changes

2022-03-23 12:37 UTC, NazarYanchyshyn commented on web/src/components/admin/ProjectPage/ProjectPage.tsx
> +const defaultProjectInfo = {
Використай реакт хук форм

2022-03-23 12:37 UTC, NazarYanchyshyn commented on web/src/components/admin/ProjectPage/ProjectPage.tsx
> +      {show ?
використай реюзабельну модалку

2022-03-23 12:37 UTC, NazarYanchyshyn commented on web/src/components/admin/ProjectPage/ProjectPage.tsx
> +const defaultProjectInfo = {
А ще краще форму реюзабельну

2022-03-23 12:55 UTC, AntonMajest commented on web/src/components/admin/ProjectPage/ProjectPage.tsx
> +        <div>
Не критично, але намагайся не створювати додаткових div-ів, у тебе вже є тег, який "огортає" всю таблицю "TabPanel", ти можеш цей div видалити, або на крайній випадок заюзати React.Fragment(<></>)

2022-03-23 21:26 UTC, AntonMajest commented on web/src/components/admin/ProjectModalForm/ProjectModalForm.tsx
> +      <div id="transition-modal-description">
По моєму коментарю все ок, лишні діви прибрані, але ти не використав нашу кастомну реюзабельну модалку, як просив Назар, а так мій комент зарезолвив +1

2022-03-23 22:36 UTC, asmlvsk commented on web/src/components/admin/ProjectModalForm/ProjectModalForm.tsx
> +      <div id="transition-modal-description">
Якщо ти про кастомний <Modal/>, то заюзав

2022-03-24 10:10 UTC, NazarYanchyshyn approved these changes

2022-03-24 10:40 UTC, merged